--- #YAML:1.0
name:               PHP-Include
version:            0.30
abstract:           Include PHP files in Perl 
author:
    - Alberto Simoes <ambs@cpan.org> and Ed Summers <ehs@pobox.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Filter::Simple:     0.78
    Parse::RecDescent:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
