# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PHP-Include
version:      0.08
version_from: lib/PHP/Include.pm
installdirs:  site
requires:
    Filter::Simple:                0.78
    Parse::RecDescent:             1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
